% This is a script to generate plots for the "Examples" page of the cppdlr
% documentation. It uses data generated by the program
% "examples/dlr_interpolation.cpp" in the cppdlr repository. This script should
% be run in the same directory as the dlr_interpolation executable, which
% generates the folder "data" used here.

export = false; % Export images using the export_fig package

load data/dlr_rf
load data/dlr_it
load data/g_dlr_it
load data/ttst
load data/gtru_t
load data/gtst_t
load data/n
load data/gtru_om
load data/gtst_om

beta = 100;
dlr_rf = dlr_rf/beta;
dlr_it = beta * dlr_it;
ttst = beta * ttst;

% Reshape Green's functions
g_dlr_it = reshape(g_dlr_it, 2, 2, []);
gtru_t = reshape(gtru_t, 2, 2, []);
gtst_t = reshape(gtst_t, 2, 2, []);
gtru_om = reshape(gtru_om(:,1)+1i*gtru_om(:,2), 2, 2, []);
gtst_om = reshape(gtst_om(:,1)+1i*gtst_om(:,2), 2, 2, []);

% Set some font sizes
ticksize = 15;
labelsize = 30;
linewidth = 2;
legendsize = 20;

% Plot 1: DLR frequencies

fig1 = figure(1);
set(1,'Position',[100 100 600 110]);
set(1, 'Color', 'white');
plot(dlr_rf,zeros(size(dlr_rf)),'.','MarkerSize',20);
yticks([]);
set(gca, 'TickLabelInterpreter', 'latex')
set(gca, 'FontSize', ticksize)
xlabel('$\omega$', 'Interpreter', 'latex', 'FontSize', labelsize)

% Plot 2: Green's function with imaginary time nodes

fig2 = figure(2);
set(2,'Position',[700 100 400 200]);
set(2, 'Color', 'white');
plot(ttst, squeeze(gtru_t(1,1,:)), '-', 'LineWidth', linewidth); hold on;
plot(dlr_it, squeeze(g_dlr_it(1,1,:)), '.', 'MarkerSize', 20); hold off;
set(gca, 'TickLabelInterpreter', 'latex')
set(gca, 'FontSize', ticksize)
xlabel('$\tau$', 'Interpreter', 'latex', 'FontSize', labelsize)
ylabel('$G_{00}(\tau)$', 'Interpreter', 'latex', 'FontSize', 25)
legend('','DLR nodes','Location','SouthEast','FontSize',legendsize,...
    'Interpreter','latex')
legend boxoff

% Plot 3: Error of imaginary time Green's function

fig3 = figure(3);
set(3,'Position',[700 400 400 220]);
set(3, 'Color', 'white');
plot(ttst, squeeze(abs(gtru_t(1,1,:)-gtst_t(1,1,:))), '-', 'LineWidth', linewidth);
set(gca, 'TickLabelInterpreter', 'latex')
set(gca, 'FontSize', ticksize)
xlabel('$\tau$', 'Interpreter', 'latex', 'FontSize', labelsize)
ylabel('$|G^{DLR}_{00}(\tau) - G^{true}_{00}(\tau)|$', 'Interpreter', 'latex', 'FontSize', 17)

% Plot 4: Error of imaginary frequency Green's function

fig4 = figure(4);
set(4,'Position',[700 700 400 220]);
set(4, 'Color', 'white');
plot((2*n+1)*pi/beta, squeeze(abs(gtru_om(1,1,:)-gtst_om(1,1,:))), '-', 'LineWidth', linewidth);
set(gca, 'TickLabelInterpreter', 'latex')
set(gca, 'FontSize', ticksize)
xlabel('$i \nu_n$', 'Interpreter', 'latex', 'FontSize', labelsize)
ylabel('$|G^{DLR}_{00}(i \nu_n) - G^{true}_{00}(i \nu_n)|$', 'Interpreter', 'latex', 'FontSize', 17)
xlim([(2*n(1)+1)*pi/beta, (2*n(end)+1)*pi/beta])

if (export)
    export_fig(fig1,'dlr_rf.png','-transparent','-r300');
    export_fig(fig2,'gfun.png','-transparent','-r300'); 
    export_fig(fig3,'gfun_err_it.png','-transparent','-r300'); 
    export_fig(fig4,'gfun_err_if.png','-transparent','-r300'); 
end
